
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v90/MS.VSIPCC.v90/ms.practices.scsf.2008apr/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace EstandarCliente.SesionMdl
{
    partial class VContrasena
    {
        /// <summary>
        /// The presenter used by this view.
        /// </summary>
        private EstandarCliente.SesionMdl.VContrasenaPresenter _presenter = null;

        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_presenter != null)
                    _presenter.Dispose();

                if (components != null)
                    components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.labelControl1 = new DevExpress.XtraEditors.LabelControl();
            this.txtContarseña = new DevExpress.XtraEditors.TextEdit();
            this.txtConfirmacion = new DevExpress.XtraEditors.TextEdit();
            this.labelControl2 = new DevExpress.XtraEditors.LabelControl();
            this.btnCancelar = new DevExpress.XtraEditors.SimpleButton();
            this.btnAceptar = new DevExpress.XtraEditors.SimpleButton();
            ((System.ComponentModel.ISupportInitialize)(this.txtContarseña.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtConfirmacion.Properties)).BeginInit();
            this.SuspendLayout();
            // 
            // labelControl1
            // 
            this.labelControl1.Location = new System.Drawing.Point(12, 12);
            this.labelControl1.Name = "labelControl1";
            this.labelControl1.Size = new System.Drawing.Size(88, 13);
            this.labelControl1.TabIndex = 3;
            this.labelControl1.Text = "Nueva contraseña";
            // 
            // txtContarseña
            // 
            this.txtContarseña.EditValue = "";
            this.txtContarseña.Location = new System.Drawing.Point(12, 31);
            this.txtContarseña.Name = "txtContarseña";
            this.txtContarseña.Properties.Appearance.Font = new System.Drawing.Font("Wingdings", 8.25F);
            this.txtContarseña.Properties.Appearance.Options.UseFont = true;
            this.txtContarseña.Size = new System.Drawing.Size(188, 19);
            this.txtContarseña.TabIndex = 0;
            // 
            // txtConfirmacion
            // 
            this.txtConfirmacion.EditValue = "";
            this.txtConfirmacion.Location = new System.Drawing.Point(12, 76);
            this.txtConfirmacion.Name = "txtConfirmacion";
            this.txtConfirmacion.Properties.Appearance.Font = new System.Drawing.Font("Wingdings", 8.25F);
            this.txtConfirmacion.Properties.Appearance.Options.UseFont = true;
            this.txtConfirmacion.Size = new System.Drawing.Size(188, 19);
            this.txtConfirmacion.TabIndex = 1;
            // 
            // labelControl2
            // 
            this.labelControl2.Location = new System.Drawing.Point(12, 57);
            this.labelControl2.Name = "labelControl2";
            this.labelControl2.Size = new System.Drawing.Size(104, 13);
            this.labelControl2.TabIndex = 4;
            this.labelControl2.Text = "Confirmar contraseña";
            // 
            // btnCancelar
            // 
            this.btnCancelar.Image = global::EstandarCliente.SesionMdl.Properties.Resources.cancelarsmall;
            this.btnCancelar.Location = new System.Drawing.Point(125, 111);
            this.btnCancelar.Name = "btnCancelar";
            this.btnCancelar.Size = new System.Drawing.Size(75, 23);
            this.btnCancelar.TabIndex = 5;
            this.btnCancelar.Text = "Cancelar";
            // 
            // btnAceptar
            // 
            this.btnAceptar.Image = global::EstandarCliente.SesionMdl.Properties.Resources.aceptarsmall;
            this.btnAceptar.Location = new System.Drawing.Point(44, 111);
            this.btnAceptar.Name = "btnAceptar";
            this.btnAceptar.Size = new System.Drawing.Size(75, 23);
            this.btnAceptar.TabIndex = 2;
            this.btnAceptar.Text = "Aceptar";
            // 
            // VContrasena
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.ClientSize = new System.Drawing.Size(209, 141);
            this.ControlBox = false;
            this.Controls.Add(this.btnCancelar);
            this.Controls.Add(this.btnAceptar);
            this.Controls.Add(this.txtConfirmacion);
            this.Controls.Add(this.labelControl2);
            this.Controls.Add(this.txtContarseña);
            this.Controls.Add(this.labelControl1);
            this.MaximumSize = new System.Drawing.Size(225, 179);
            this.MinimumSize = new System.Drawing.Size(225, 179);
            this.Name = "VContrasena";
            this.SizeGripStyle = System.Windows.Forms.SizeGripStyle.Hide;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Cambiar contraseña";
            this.TopMost = true;
            ((System.ComponentModel.ISupportInitialize)(this.txtContarseña.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtConfirmacion.Properties)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private DevExpress.XtraEditors.LabelControl labelControl1;
        private DevExpress.XtraEditors.TextEdit txtContarseña;
        private DevExpress.XtraEditors.TextEdit txtConfirmacion;
        private DevExpress.XtraEditors.LabelControl labelControl2;
        private DevExpress.XtraEditors.SimpleButton btnAceptar;
        private DevExpress.XtraEditors.SimpleButton btnCancelar;
    }
}

