//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.6407
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstadoDispensarios
{
    using System;
    using RemObjects.SDK;
    using RemObjects.SDK.Types;
    using System.Collections.Generic;

    public interface ISrvDispensarios : RemObjects.SDK.IROService
    {
        string DameDispensarios();
    }
    public partial class SrvDispensarios_Proxy : RemObjects.SDK.Proxy, ISrvDispensarios
    {
        public SrvDispensarios_Proxy(RemObjects.SDK.IMessage aMessage, RemObjects.SDK.IClientChannel aClientChannel) :
            base(aMessage, aClientChannel)
        {
        }
        public SrvDispensarios_Proxy(RemObjects.SDK.IMessage aMessage, RemObjects.SDK.IClientChannel aClientChannel, string aOverrideInterfaceName) :
            base(aMessage, aClientChannel, aOverrideInterfaceName)
        {
        }
        public SrvDispensarios_Proxy(RemObjects.SDK.IRemoteService aRemoteService) :
            base(aRemoteService)
        {
        }
        public SrvDispensarios_Proxy(RemObjects.SDK.IRemoteService aRemoteService, string aOverrideInterfaceName) :
            base(aRemoteService, aOverrideInterfaceName)
        {
        }
        protected override string @__GetInterfaceName()
        {
            return "SrvDispensarios";
        }
        public virtual string DameDispensarios()
        {
            @__Message.InitializeRequestMessage(@__ClientChannel, "DmSrv", @__GetActiveInterfaceName(), "DameDispensarios");
            @__Message.FinalizeMessage();
            @__ClientChannel.Dispatch(@__Message);
            string Result = @__Message.ReadAnsiString("Result");
            @__Message.Clear();
            return Result;
        }
    }
    public class CoSrvDispensarios
    {
        public static ISrvDispensarios Create(RemObjects.SDK.IMessage aMessage, RemObjects.SDK.IClientChannel aClientChannel)
        {
            return new SrvDispensarios_Proxy(aMessage, aClientChannel);
        }
        public static ISrvDispensarios Create(RemObjects.SDK.IRemoteService aRemoteService)
        {
            return new SrvDispensarios_Proxy(aRemoteService);
        }
    }
}
