//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstandarCliente.Infrastructure.Interface.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ListadoMensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ListadoMensajes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EstandarCliente.Infrastructure.Interface.Properties.ListadoMensajes", typeof(ListadoMensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los filtros han cambiado desde la última consulta..
        /// </summary>
        public static string Advertencia_Filtro_Consulta {
            get {
                return ResourceManager.GetString("Advertencia_Filtro_Consulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertencia: R.F.C. ya existe con el cliente {0}  {1}. Favor de revisar antes de continuar..
        /// </summary>
        public static string Advertencia_RFC_Existe {
            get {
                return ResourceManager.GetString("Advertencia_RFC_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea cancelar el cambio de cotización seleccionado?.
        /// </summary>
        public static string Confirmacion_CambioCotizacion_DeseaCancelarSeleccionado {
            get {
                return ResourceManager.GetString("Confirmacion_CambioCotizacion_DeseaCancelarSeleccionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea depurar el cambio de cotización seleccionado?.
        /// </summary>
        public static string Confirmacion_CambioCotizacion_DeseaDepurarSeleccionado {
            get {
                return ResourceManager.GetString("Confirmacion_CambioCotizacion_DeseaDepurarSeleccionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea imprimir el cambio de cotización?.
        /// </summary>
        public static string Confirmacion_CambioCotizacion_DeseaImprimir {
            get {
                return ResourceManager.GetString("Confirmacion_CambioCotizacion_DeseaImprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea cancelar los cambios?.
        /// </summary>
        public static string Confirmacion_Cancelar {
            get {
                return ResourceManager.GetString("Confirmacion_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea cancelar el Documento {0}?.
        /// </summary>
        public static string Confirmacion_Cancelar_Documento {
            get {
                return ResourceManager.GetString("Confirmacion_Cancelar_Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La columna {0} no permite tener valores vacíos. ¿Desea corregir el valor?.
        /// </summary>
        public static string Confirmacion_Columna_Vacia {
            get {
                return ResourceManager.GetString("Confirmacion_Columna_Vacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea depurar el Registro &quot;{0} - {1}&quot;?.
        /// </summary>
        public static string Confirmacion_Depurar {
            get {
                return ResourceManager.GetString("Confirmacion_Depurar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea depurar el Documento {0}?.
        /// </summary>
        public static string Confirmacion_Depurar_Documento {
            get {
                return ResourceManager.GetString("Confirmacion_Depurar_Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea eliminar el Registro &quot;{0} - {1}&quot;?.
        /// </summary>
        public static string Confirmacion_Eliminar {
            get {
                return ResourceManager.GetString("Confirmacion_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea eliminar {0}?.
        /// </summary>
        public static string Confirmacion_Eliminar_02 {
            get {
                return ResourceManager.GetString("Confirmacion_Eliminar_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea cerrar la fecha de trabajo {0} en {1}?.
        /// </summary>
        public static string Confirmacion_Fecha_Trabajo_Cerrar {
            get {
                return ResourceManager.GetString("Confirmacion_Fecha_Trabajo_Cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea eliminar la fecha de trabajo {0} en {1}?.
        /// </summary>
        public static string Confirmacion_Fecha_Trabajo_Eliminar {
            get {
                return ResourceManager.GetString("Confirmacion_Fecha_Trabajo_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea reabrir la fecha de trabajo {0} en {1}?.
        /// </summary>
        public static string Confirmacion_Fecha_Trabajo_Reabrir {
            get {
                return ResourceManager.GetString("Confirmacion_Fecha_Trabajo_Reabrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea generar un Anticipo por el importe sobrante?.
        /// </summary>
        public static string Confirmacion_Generar_Anticipo {
            get {
                return ResourceManager.GetString("Confirmacion_Generar_Anticipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea salir sin Guardar?.
        /// </summary>
        public static string Confirmacion_Guardar {
            get {
                return ResourceManager.GetString("Confirmacion_Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea imprimir el Documento?.
        /// </summary>
        public static string Confirmacion_Imprimir {
            get {
                return ResourceManager.GetString("Confirmacion_Imprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este proceso puede tardar en realizarse, ¿Desea Continuar?.
        /// </summary>
        public static string Confirmacion_Proceso_Largo {
            get {
                return ResourceManager.GetString("Confirmacion_Proceso_Largo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un registro en modo {0}, ciérrelo antes de continuar..
        /// </summary>
        public static string Error_Accion_Accedida {
            get {
                return ResourceManager.GetString("Error_Accion_Accedida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible “{0}”. Para más información consulte Bitácora de excepciones..
        /// </summary>
        public static string Error_Accion_No_Realizada {
            get {
                return ResourceManager.GetString("Error_Accion_No_Realizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible {0}..
        /// </summary>
        public static string Error_Accion_No_Realizada_SB {
            get {
                return ResourceManager.GetString("Error_Accion_No_Realizada_SB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Anticipo ya ha sido aplicado..
        /// </summary>
        public static string Error_Anticipo_Aplicado {
            get {
                return ResourceManager.GetString("Error_Anticipo_Aplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El anticipo {0} se encuentra cancelado..
        /// </summary>
        public static string Error_Anticipo_Cancelado {
            get {
                return ResourceManager.GetString("Error_Anticipo_Cancelado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe un cambio de cotización posterior a la fecha seleccionada..
        /// </summary>
        public static string Error_CambioCotizacion_ExisteCambioPosterior {
            get {
                return ResourceManager.GetString("Error_CambioCotizacion_ExisteCambioPosterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de trabajo está cerrada..
        /// </summary>
        public static string Error_CambioCotizacion_FechaTrabajoCerrada {
            get {
                return ResourceManager.GetString("Error_CambioCotizacion_FechaTrabajoCerrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de trabajo no existe..
        /// </summary>
        public static string Error_CambioCotizacion_FechaTrabajoNoExiste {
            get {
                return ResourceManager.GetString("Error_CambioCotizacion_FechaTrabajoNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible cancelar, existe un cambio de cotización con fecha posterior al seleccionado..
        /// </summary>
        public static string Error_CambioCotizacion_NoEsPosibleCancelar {
            get {
                return ResourceManager.GetString("Error_CambioCotizacion_NoEsPosibleCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible depurar cambio de cotización porque está siendo utilizado..
        /// </summary>
        public static string Error_CambioCotizacion_NoEsPosibleDepurar {
            get {
                return ResourceManager.GetString("Error_CambioCotizacion_NoEsPosibleDepurar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se han obtenido {0}..
        /// </summary>
        public static string Error_CambioCotizacion_NoSeHaObtenidoDetalle {
            get {
                return ResourceManager.GetString("Error_CambioCotizacion_NoSeHaObtenidoDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede depurar, el cambio de cotización está activo..
        /// </summary>
        public static string Error_CambioCotizacion_NoSePuedeDepurar {
            get {
                return ResourceManager.GetString("Error_CambioCotizacion_NoSePuedeDepurar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible acceder, otro usuario está utilizando el cambio de cotización..
        /// </summary>
        public static string Error_CambioCotizacion_SeEncuentraAccedido {
            get {
                return ResourceManager.GetString("Error_CambioCotizacion_SeEncuentraAccedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un cambio de cotización a abonos en la sucursal, fecha y moneda seleccionados..
        /// </summary>
        public static string Error_CambioCotizacion_YaExisteCambioCotizacion {
            get {
                return ResourceManager.GetString("Error_CambioCotizacion_YaExisteCambioCotizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cambio de cotización ya ha sido cacelado..
        /// </summary>
        public static string Error_CambioCotizacion_YaHaSidoCancelado {
            get {
                return ResourceManager.GetString("Error_CambioCotizacion_YaHaSidoCancelado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cambio de cotización ya ha sido depurado..
        /// </summary>
        public static string Error_CambioCotizacion_YaHaSidoDepurado {
            get {
                return ResourceManager.GetString("Error_CambioCotizacion_YaHaSidoDepurado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cargo {0} se encuentra cancelado..
        /// </summary>
        public static string Error_Cargo_Cancelado {
            get {
                return ResourceManager.GetString("Error_Cargo_Cancelado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cargo {0} se encuentra saldado..
        /// </summary>
        public static string Error_Cargo_Saldado {
            get {
                return ResourceManager.GetString("Error_Cargo_Saldado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cargo {0} ya existe en la lista..
        /// </summary>
        public static string Error_Cargo_Ya_Existe_En_La_Lista {
            get {
                return ResourceManager.GetString("Error_Cargo_Ya_Existe_En_La_Lista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los cargos {0} ya existen en la lista..
        /// </summary>
        public static string Error_Cargos_Ya_Existen_En_La_Lista {
            get {
                return ResourceManager.GetString("Error_Cargos_Ya_Existen_En_La_Lista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe cerrar el archivo descargado para continuar..
        /// </summary>
        public static string Error_Cerrar_Archivo_Descargado {
            get {
                return ResourceManager.GetString("Error_Cerrar_Archivo_Descargado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La clave default de {0} no existe y el usuario no tiene derechos de seleccionar..
        /// </summary>
        public static string Error_Clave_Default_No_Existe {
            get {
                return ResourceManager.GetString("Error_Clave_Default_No_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cargo {0} no pertenece al cliente {1}..
        /// </summary>
        public static string Error_Cliente_Diferente {
            get {
                return ResourceManager.GetString("Error_Cliente_Diferente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El anticipo {0} no pertenece al cliente {1}..
        /// </summary>
        public static string Error_Cliente_Diferente_Anticipo {
            get {
                return ResourceManager.GetString("Error_Cliente_Diferente_Anticipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente no tiene cargos pendientes..
        /// </summary>
        public static string Error_Cliente_No_Tiene_Cargos {
            get {
                return ResourceManager.GetString("Error_Cliente_No_Tiene_Cargos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede registrar, ya que no existen registros activos en {2}..
        /// </summary>
        public static string Error_De_Dependencia_Activas_Documento_Catalogo {
            get {
                return ResourceManager.GetString("Error_De_Dependencia_Activas_Documento_Catalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede acceder al {0} de {1}, ya que no existen registros en {2}..
        /// </summary>
        public static string Error_De_Dependencia_Documento_Catalogo {
            get {
                return ResourceManager.GetString("Error_De_Dependencia_Documento_Catalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} debe ser {1} a {2}..
        /// </summary>
        public static string Error_Debe_Ser {
            get {
                return ResourceManager.GetString("Error_Debe_Ser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario {0} no cuenta con derechos suficientes..
        /// </summary>
        public static string Error_Derechos_Usuarios {
            get {
                return ResourceManager.GetString("Error_Derechos_Usuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La lista de {0} es inválida..
        /// </summary>
        public static string Error_Detalle_Invalido {
            get {
                return ResourceManager.GetString("Error_Detalle_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El día {0} ya está asignado..
        /// </summary>
        public static string Error_Dia_Asignado {
            get {
                return ResourceManager.GetString("Error_Dia_Asignado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Documento se encuentra accedido por otro usuario..
        /// </summary>
        public static string Error_Documento_Accedido_Usuario {
            get {
                return ResourceManager.GetString("Error_Documento_Accedido_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Documento ya ha sido cancelado..
        /// </summary>
        public static string Error_Documento_Cancelado {
            get {
                return ResourceManager.GetString("Error_Documento_Cancelado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Documento {0} tiene una referencia a {1}..
        /// </summary>
        public static string Error_Documento_Con_Referencia {
            get {
                return ResourceManager.GetString("Error_Documento_Con_Referencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Documento ya ha sido depurado..
        /// </summary>
        public static string Error_Documento_Depurado {
            get {
                return ResourceManager.GetString("Error_Documento_Depurado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Documento es una cancelación..
        /// </summary>
        public static string Error_Documento_Es_Cancelacion {
            get {
                return ResourceManager.GetString("Error_Documento_Es_Cancelacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extención inválida para {0}..
        /// </summary>
        public static string Error_Extencion_Invalida {
            get {
                return ResourceManager.GetString("Error_Extencion_Invalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha proporcionada no debe ser mayor a la fecha actual..
        /// </summary>
        public static string Error_Fecha_Actual {
            get {
                return ResourceManager.GetString("Error_Fecha_Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha del cargo {0} es mayor a la fecha de {1}..
        /// </summary>
        public static string Error_Fecha_Diferente {
            get {
                return ResourceManager.GetString("Error_Fecha_Diferente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha del anticipo {0} es mayor a la fecha de {1}..
        /// </summary>
        public static string Error_Fecha_Diferente_Anticipo {
            get {
                return ResourceManager.GetString("Error_Fecha_Diferente_Anticipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Inicial no debe ser mayor a la Fecha Final..
        /// </summary>
        public static string Error_Fecha_Mayor {
            get {
                return ResourceManager.GetString("Error_Fecha_Mayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de trabajo está abierta..
        /// </summary>
        public static string Error_Fecha_Trabajo_Abierta {
            get {
                return ResourceManager.GetString("Error_Fecha_Trabajo_Abierta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de trabajo está cerrada a la fecha indicada..
        /// </summary>
        public static string Error_Fecha_Trabajo_Cerrada {
            get {
                return ResourceManager.GetString("Error_Fecha_Trabajo_Cerrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de trabajo está cerrada al día {0} en {1}..
        /// </summary>
        public static string Error_Fecha_Trabajo_Cerrada_Sucursal {
            get {
                return ResourceManager.GetString("Error_Fecha_Trabajo_Cerrada_Sucursal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de trabajo del Documento ya ha sido cerrada.
        /// </summary>
        public static string Error_Fecha_Trabajo_Documento_Cerrada {
            get {
                return ResourceManager.GetString("Error_Fecha_Trabajo_Documento_Cerrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de trabajo del documento no existe..
        /// </summary>
        public static string Error_Fecha_Trabajo_Documento_No_Existe {
            get {
                return ResourceManager.GetString("Error_Fecha_Trabajo_Documento_No_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de trabajo ya ha sido eliminada..
        /// </summary>
        public static string Error_Fecha_Trabajo_Eliminada {
            get {
                return ResourceManager.GetString("Error_Fecha_Trabajo_Eliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de trabajo no se puede eliminar ya que existen movimientos registrados..
        /// </summary>
        public static string Error_Fecha_Trabajo_Eliminar {
            get {
                return ResourceManager.GetString("Error_Fecha_Trabajo_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de trabajo no está cerrada al día {0} en la Sucursal {1}..
        /// </summary>
        public static string Error_Fecha_Trabajo_No_Cerrada {
            get {
                return ResourceManager.GetString("Error_Fecha_Trabajo_No_Cerrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de trabajo no existe a la fecha indicada..
        /// </summary>
        public static string Error_Fecha_Trabajo_No_Existe {
            get {
                return ResourceManager.GetString("Error_Fecha_Trabajo_No_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de trabajo no existe al día {0} en {1}..
        /// </summary>
        public static string Error_Fecha_Trabajo_No_Existe_Sucursal {
            get {
                return ResourceManager.GetString("Error_Fecha_Trabajo_No_Existe_Sucursal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de trabajo no se puede eliminar ya que existen pólizas generadas..
        /// </summary>
        public static string Error_Fecha_Trabajo_No_Se_Puede_Eliminar {
            get {
                return ResourceManager.GetString("Error_Fecha_Trabajo_No_Se_Puede_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de trabajo no se puede reabrir ya que existen pólizas generadas..
        /// </summary>
        public static string Error_Fecha_Trabajo_No_Se_Puede_Reabrir {
            get {
                return ResourceManager.GetString("Error_Fecha_Trabajo_No_Se_Puede_Reabrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de trabajo ya ha sido cerrada..
        /// </summary>
        public static string Error_Fecha_Trabajo_Ya_Ha_Sido_Cerrada {
            get {
                return ResourceManager.GetString("Error_Fecha_Trabajo_Ya_Ha_Sido_Cerrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cargo {0} no tiene el mismo giro de venta que {1}..
        /// </summary>
        public static string Error_Giro_Venta_Diferente {
            get {
                return ResourceManager.GetString("Error_Giro_Venta_Diferente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora de Inicio no debe ser mayor a la Hora de Fin..
        /// </summary>
        public static string Error_Hora_Mayor {
            get {
                return ResourceManager.GetString("Error_Hora_Mayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La suma del importe de los Cargos es mayor al importe de {0}..
        /// </summary>
        public static string Error_Importe_Cargos_Es_Mayor {
            get {
                return ResourceManager.GetString("Error_Importe_Cargos_Es_Mayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El importe de {0} es mayor que la suma del importe de los Cargos..
        /// </summary>
        public static string Error_Importe_Documento_Es_Mayor {
            get {
                return ResourceManager.GetString("Error_Importe_Documento_Es_Mayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El importe total en {0} de los Cargos es mayor al importe en {0} de {1}..
        /// </summary>
        public static string Error_Importe_Moneda_Cargo_Es_Mayor {
            get {
                return ResourceManager.GetString("Error_Importe_Moneda_Cargo_Es_Mayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El importe en {0} de {1} es mayor que el importe total en {0} de los Cargos..
        /// </summary>
        public static string Error_Importe_Moneda_Documento_Es_Mayor {
            get {
                return ResourceManager.GetString("Error_Importe_Moneda_Documento_Es_Mayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El módulo {0} no se encontró..
        /// </summary>
        public static string Error_Modulo_No_Encontrado {
            get {
                return ResourceManager.GetString("Error_Modulo_No_Encontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La moneda del cargo {0} no tienen paridad a la fecha en que se registró el anticipo..
        /// </summary>
        public static string Error_Moneda_Cargo_Sin_Paridad_Fecha_Anticipo {
            get {
                return ResourceManager.GetString("Error_Moneda_Cargo_Sin_Paridad_Fecha_Anticipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las monedas de los cargos {0} no tienen paridad a la fecha en que se registro el anticipo..
        /// </summary>
        public static string Error_Moneda_Cargos_Sin_Paridad_Fecha_Anticipo {
            get {
                return ResourceManager.GetString("Error_Moneda_Cargos_Sin_Paridad_Fecha_Anticipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cargo {0} no tiene la misma moneda que {1}..
        /// </summary>
        public static string Error_Moneda_Diferente {
            get {
                return ResourceManager.GetString("Error_Moneda_Diferente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} no acepta espacios en blanco..
        /// </summary>
        public static string Error_No_Acepta_Espacios_En_Blanco {
            get {
                return ResourceManager.GetString("Error_No_Acepta_Espacios_En_Blanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró ruta de base de datos en la Sucursal {0} - {1}.
        /// </summary>
        public static string Error_No_Encontro_RutaBD {
            get {
                return ResourceManager.GetString("Error_No_Encontro_RutaBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El importe en {0} de la Aplicación de Anticipo es mayor que el importe total en {0} de los cargos y no es posible generar un anticipo automático con el importe sobrante ya que no existe paridad a la fecha en la moneda del anticipo..
        /// </summary>
        public static string Error_No_Es_Posible_Generar_Anticipo_Automatico {
            get {
                return ResourceManager.GetString("Error_No_Es_Posible_Generar_Anticipo_Automatico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe {0}..
        /// </summary>
        public static string Error_No_Existe {
            get {
                return ResourceManager.GetString("Error_No_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe configuración para la sucursal con clave {0}..
        /// </summary>
        public static string Error_No_Existe_Configuracion {
            get {
                return ResourceManager.GetString("Error_No_Existe_Configuracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible registrar, ya que no existe paridad al día..
        /// </summary>
        public static string Error_No_Existe_Paridad_Al_Dia {
            get {
                return ResourceManager.GetString("Error_No_Existe_Paridad_Al_Dia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe paridad a la fecha indicada..
        /// </summary>
        public static string Error_No_Existe_Paridad_Fecha_Indicada {
            get {
                return ResourceManager.GetString("Error_No_Existe_Paridad_Fecha_Indicada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe paridad a la fecha y moneda indicada..
        /// </summary>
        public static string Error_No_Existe_Paridad_Fecha_Moneda_Indicada {
            get {
                return ResourceManager.GetString("Error_No_Existe_Paridad_Fecha_Moneda_Indicada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay configuraciones de pólizas en la Sucursal {0} - {1}..
        /// </summary>
        public static string Error_No_Hay_Configuracion_Polizas {
            get {
                return ResourceManager.GetString("Error_No_Hay_Configuracion_Polizas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede crear la impresión..
        /// </summary>
        public static string Error_No_Se_Pudo_Crear_Impresion {
            get {
                return ResourceManager.GetString("Error_No_Se_Pudo_Crear_Impresion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede cancelar, ya que fue generado por una Aplicación de Anticipos..
        /// </summary>
        public static string Error_No_Se_Puede_Cancelar_Anticipo_Generado {
            get {
                return ResourceManager.GetString("Error_No_Se_Puede_Cancelar_Anticipo_Generado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede cancelar, el Anticipo automático ya fue aplicado..
        /// </summary>
        public static string Error_No_Se_Puede_Cancelar_Aplicacion_Anticipo {
            get {
                return ResourceManager.GetString("Error_No_Se_Puede_Cancelar_Aplicacion_Anticipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Registro &quot;{0} - {1}&quot; no puede ser cancelar por que está siendo utilizado..
        /// </summary>
        public static string Error_No_Se_Puede_Cancelar_Documento {
            get {
                return ResourceManager.GetString("Error_No_Se_Puede_Cancelar_Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Registro no puede ser eliminado por que está siendo utilizado..
        /// </summary>
        public static string Error_No_Se_Puede_Cancelar_Documento_SP {
            get {
                return ResourceManager.GetString("Error_No_Se_Puede_Cancelar_Documento_SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede conectar a la base de datos en la ruta {0}..
        /// </summary>
        public static string Error_No_Se_Puede_Conectar_BD {
            get {
                return ResourceManager.GetString("Error_No_Se_Puede_Conectar_BD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede Depurar, el registro está activo..
        /// </summary>
        public static string Error_No_se_puede_Depurar {
            get {
                return ResourceManager.GetString("Error_No_se_puede_Depurar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede depurar, ya que fue generado por una Aplicación de Anticipos..
        /// </summary>
        public static string Error_No_Se_Puede_Depurar_Anticipo_Generado {
            get {
                return ResourceManager.GetString("Error_No_Se_Puede_Depurar_Anticipo_Generado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede depurar, el Anticipo automático está activo..
        /// </summary>
        public static string Error_No_Se_Puede_Depurar_Aplicacion_Anticipo {
            get {
                return ResourceManager.GetString("Error_No_Se_Puede_Depurar_Aplicacion_Anticipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede depurar, el Documento está activo..
        /// </summary>
        public static string Error_No_se_puede_Depurar_Documento_Activo {
            get {
                return ResourceManager.GetString("Error_No_se_puede_Depurar_Documento_Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Documento {0} no puede ser depurado porque está siendo utilizado..
        /// </summary>
        public static string Error_No_se_puede_Depurar_Documento_Utilizado {
            get {
                return ResourceManager.GetString("Error_No_se_puede_Depurar_Documento_Utilizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Registro &quot;{0} - {1}&quot; no puede ser eliminado por que está siendo utilizado..
        /// </summary>
        public static string Error_No_se_puede_Eliminar {
            get {
                return ResourceManager.GetString("Error_No_se_puede_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Registro no puede ser eliminado por que está siendo utilizado..
        /// </summary>
        public static string Error_No_se_puede_Eliminar_SP {
            get {
                return ResourceManager.GetString("Error_No_se_puede_Eliminar_SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se han registrado {0}..
        /// </summary>
        public static string Error_No_Se_Registraron_Detalles {
            get {
                return ResourceManager.GetString("Error_No_Se_Registraron_Detalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La plantilla que se utiliza para la impresión de este documento esta abierta. ¡Debe cerrarla!.
        /// </summary>
        public static string Error_Plantilla_Abierta {
            get {
                return ResourceManager.GetString("Error_Plantilla_Abierta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La plantilla que se utiliza para la impresión no Existe, ruta: {0}.
        /// </summary>
        public static string Error_Plantilla_No_Existe {
            get {
                return ResourceManager.GetString("Error_Plantilla_No_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor de los rangos es inválido..
        /// </summary>
        public static string Error_Rangos_Invalidos {
            get {
                return ResourceManager.GetString("Error_Rangos_Invalidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} se encuentra accedida por otro usuario..
        /// </summary>
        public static string Error_Registro_Accedida_Usuario {
            get {
                return ResourceManager.GetString("Error_Registro_Accedida_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} se encuentra accedido por otro usuario..
        /// </summary>
        public static string Error_Registro_Accedido_Usuario {
            get {
                return ResourceManager.GetString("Error_Registro_Accedido_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede Eliminar, el registro está activo..
        /// </summary>
        public static string Error_Registro_Activo {
            get {
                return ResourceManager.GetString("Error_Registro_Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Registro ya ha sido eliminado..
        /// </summary>
        public static string Error_Registro_Eliminado {
            get {
                return ResourceManager.GetString("Error_Registro_Eliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro no puede ser Modificado y Eliminado al mismo tiempo..
        /// </summary>
        public static string Error_Registro_En_Edicion {
            get {
                return ResourceManager.GetString("Error_Registro_En_Edicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una opción de {0}..
        /// </summary>
        public static string Error_Seleccione_Opcion {
            get {
                return ResourceManager.GetString("Error_Seleccione_Opcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe sesion del sistema.
        /// </summary>
        public static string Error_Sesion_No_Existe {
            get {
                return ResourceManager.GetString("Error_Sesion_No_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cargo {0} no tiene la misma sucursal que {1}..
        /// </summary>
        public static string Error_Sucursal_Diferente {
            get {
                return ResourceManager.GetString("Error_Sucursal_Diferente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El anticipo {0} no tiene la misma sucursal que {1}..
        /// </summary>
        public static string Error_Sucursal_Diferente_Anticipo {
            get {
                return ResourceManager.GetString("Error_Sucursal_Diferente_Anticipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamaño inválido para {0}..
        /// </summary>
        public static string Error_Tamaño_Invalido {
            get {
                return ResourceManager.GetString("Error_Tamaño_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Turno está cerrado..
        /// </summary>
        public static string Error_Turno_Cerrado {
            get {
                return ResourceManager.GetString("Error_Turno_Cerrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor de {0} no puede quedar vacío..
        /// </summary>
        public static string Error_Vacio {
            get {
                return ResourceManager.GetString("Error_Vacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} ya existe..
        /// </summary>
        public static string Error_Valor_Existe {
            get {
                return ResourceManager.GetString("Error_Valor_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} ya existen..
        /// </summary>
        public static string Error_Valor_Existen {
            get {
                return ResourceManager.GetString("Error_Valor_Existen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} está inactiva..
        /// </summary>
        public static string Error_Valor_Inactiva {
            get {
                return ResourceManager.GetString("Error_Valor_Inactiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} está inactivo..
        /// </summary>
        public static string Error_Valor_Inactivo {
            get {
                return ResourceManager.GetString("Error_Valor_Inactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Inválido para {0}..
        /// </summary>
        public static string Error_Valor_Invalido {
            get {
                return ResourceManager.GetString("Error_Valor_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} acepta valores de {1} a {2}..
        /// </summary>
        public static string Error_Valor_Longitud {
            get {
                return ResourceManager.GetString("Error_Valor_Longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} no existe.
        /// </summary>
        public static string Error_Valor_No_Existe {
            get {
                return ResourceManager.GetString("Error_Valor_No_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cargo {0} esta documentado con el folio {1}..
        /// </summary>
        public static string Informacion_Cargo_Documentado {
            get {
                return ResourceManager.GetString("Informacion_Cargo_Documentado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha del cargo {0} es mayor a la del documento..
        /// </summary>
        public static string Informacion_Cargo_Fecha_Mayor_Documento {
            get {
                return ResourceManager.GetString("Informacion_Cargo_Fecha_Mayor_Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cargo {0} ya existe en el contrarecibo {1}.
        /// </summary>
        public static string Informacion_Cargo_Ya_Existe_Asignado {
            get {
                return ResourceManager.GetString("Informacion_Cargo_Ya_Existe_Asignado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} se Guardó con el folio “{1}”..
        /// </summary>
        public static string Informacion_Documento_Folio_Recalculado {
            get {
                return ResourceManager.GetString("Informacion_Documento_Folio_Recalculado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron registros con los parámetros seleccionados..
        /// </summary>
        public static string Informacion_No_Encontro_Registros {
            get {
                return ResourceManager.GetString("Informacion_No_Encontro_Registros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay movimientos generados para la póliza..
        /// </summary>
        public static string Informacion_No_Hay_Movimientos {
            get {
                return ResourceManager.GetString("Informacion_No_Hay_Movimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro fue depurado correctamente..
        /// </summary>
        public static string Informacion_Registro_Depurado {
            get {
                return ResourceManager.GetString("Informacion_Registro_Depurado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} no tiene un {1} relacionado.
        /// </summary>
        public static string Informacion_Sin_Detalle {
            get {
                return ResourceManager.GetString("Informacion_Sin_Detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} ya existe, el registro se guardó con {0} {2}..
        /// </summary>
        public static string Informacion_Valor_Existe_No_Administrado {
            get {
                return ResourceManager.GetString("Informacion_Valor_Existe_No_Administrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} ya existe, el registro se guardará con {0} {2}..
        /// </summary>
        public static string Informacion_Valor_Existe_No_Administrado_Guardara {
            get {
                return ResourceManager.GetString("Informacion_Valor_Existe_No_Administrado_Guardara", resourceCulture);
            }
        }
    }
}
