
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v90/MS.VSIPCC.v90/ms.practices.scsf.2008apr/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace EstandarCliente.AdministrarClientesMdl
{
    partial class VMAdministrarClientes
    {
        /// <summary>
        /// The presenter used by this view.
        /// </summary>
        private EstandarCliente.AdministrarClientesMdl.VMAdministrarClientesPresenter _presenter = null;

        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_presenter != null)
                    _presenter.Dispose();

                if (components != null)
                    components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.titulo1 = new ControlesEstandar.Titulo();
            this.labelControl2 = new DevExpress.XtraEditors.LabelControl();
            this.txtNombreComercial = new DevExpress.XtraEditors.TextEdit();
            this.txtNoEstacion = new DevExpress.XtraEditors.TextEdit();
            this.labelControl4 = new DevExpress.XtraEditors.LabelControl();
            this.groupControl1 = new DevExpress.XtraEditors.GroupControl();
            this.chkActivo = new DevExpress.XtraEditors.CheckEdit();
            this.txtFechaUltimoCambio = new DevExpress.XtraEditors.TextEdit();
            this.labelControl6 = new DevExpress.XtraEditors.LabelControl();
            this.txtFechaAlta = new DevExpress.XtraEditors.TextEdit();
            this.labelControl5 = new DevExpress.XtraEditors.LabelControl();
            this.groupControl2 = new DevExpress.XtraEditors.GroupControl();
            this.pnlContent = new DevExpress.XtraEditors.PanelControl();
            this.groupControl7 = new DevExpress.XtraEditors.GroupControl();
            this.txtMatriz = new DevExpress.XtraEditors.ButtonEdit();
            this.labelControl13 = new DevExpress.XtraEditors.LabelControl();
            this.labelControl12 = new DevExpress.XtraEditors.LabelControl();
            this.txtHostPuerto = new DevExpress.XtraEditors.TextEdit();
            this.groupControl3 = new DevExpress.XtraEditors.GroupControl();
            this.luDistribuidor = new DevExpress.XtraEditors.LookUpEdit();
            this.labelControl11 = new DevExpress.XtraEditors.LabelControl();
            this.txtContacto = new DevExpress.XtraEditors.TextEdit();
            this.labelControl3 = new DevExpress.XtraEditors.LabelControl();
            this.txtTelefono = new DevExpress.XtraEditors.TextEdit();
            this.labelControl8 = new DevExpress.XtraEditors.LabelControl();
            this.txtEMail = new DevExpress.XtraEditors.TextEdit();
            this.labelControl7 = new DevExpress.XtraEditors.LabelControl();
            this.pnlDomicilios = new DevExpress.XtraEditors.PanelControl();
            ((System.ComponentModel.ISupportInitialize)(this.txtNombreComercial.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtNoEstacion.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.groupControl1)).BeginInit();
            this.groupControl1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.chkActivo.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtFechaUltimoCambio.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtFechaAlta.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.groupControl2)).BeginInit();
            this.groupControl2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pnlContent)).BeginInit();
            this.pnlContent.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.groupControl7)).BeginInit();
            this.groupControl7.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.txtMatriz.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtHostPuerto.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.groupControl3)).BeginInit();
            this.groupControl3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.luDistribuidor.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtContacto.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtTelefono.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtEMail.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pnlDomicilios)).BeginInit();
            this.pnlDomicilios.SuspendLayout();
            this.SuspendLayout();
            // 
            // titulo1
            // 
            this.titulo1.BackColor1 = System.Drawing.Color.LightSkyBlue;
            this.titulo1.BackColor2 = System.Drawing.Color.RoyalBlue;
            this.titulo1.Dock = System.Windows.Forms.DockStyle.Top;
            this.titulo1.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.titulo1.Location = new System.Drawing.Point(0, 0);
            this.titulo1.Name = "titulo1";
            this.titulo1.Size = new System.Drawing.Size(909, 50);
            this.titulo1.TabIndex = 0;
            this.titulo1.TituloMenu = null;
            // 
            // labelControl2
            // 
            this.labelControl2.Location = new System.Drawing.Point(92, 23);
            this.labelControl2.Name = "labelControl2";
            this.labelControl2.Size = new System.Drawing.Size(86, 13);
            this.labelControl2.TabIndex = 3;
            this.labelControl2.Text = "Nombre Comercial";
            // 
            // txtNombreComercial
            // 
            this.txtNombreComercial.Location = new System.Drawing.Point(92, 42);
            this.txtNombreComercial.Name = "txtNombreComercial";
            this.txtNombreComercial.Size = new System.Drawing.Size(294, 20);
            this.txtNombreComercial.TabIndex = 1;
            // 
            // txtNoEstacion
            // 
            this.txtNoEstacion.EditValue = "";
            this.txtNoEstacion.Location = new System.Drawing.Point(5, 42);
            this.txtNoEstacion.Name = "txtNoEstacion";
            this.txtNoEstacion.Size = new System.Drawing.Size(81, 20);
            this.txtNoEstacion.TabIndex = 0;
            // 
            // labelControl4
            // 
            this.labelControl4.Location = new System.Drawing.Point(5, 23);
            this.labelControl4.Name = "labelControl4";
            this.labelControl4.Size = new System.Drawing.Size(60, 13);
            this.labelControl4.TabIndex = 2;
            this.labelControl4.Text = "No. Estación";
            // 
            // groupControl1
            // 
            this.groupControl1.Controls.Add(this.chkActivo);
            this.groupControl1.Controls.Add(this.txtFechaUltimoCambio);
            this.groupControl1.Controls.Add(this.labelControl6);
            this.groupControl1.Controls.Add(this.txtFechaAlta);
            this.groupControl1.Controls.Add(this.labelControl5);
            this.groupControl1.Location = new System.Drawing.Point(3, 255);
            this.groupControl1.Name = "groupControl1";
            this.groupControl1.Size = new System.Drawing.Size(392, 71);
            this.groupControl1.TabIndex = 2;
            this.groupControl1.Text = "Información";
            // 
            // chkActivo
            // 
            this.chkActivo.Location = new System.Drawing.Point(175, 42);
            this.chkActivo.Name = "chkActivo";
            this.chkActivo.Properties.Caption = "Activo";
            this.chkActivo.Size = new System.Drawing.Size(54, 19);
            this.chkActivo.TabIndex = 1;
            // 
            // txtFechaUltimoCambio
            // 
            this.txtFechaUltimoCambio.Location = new System.Drawing.Point(235, 41);
            this.txtFechaUltimoCambio.Name = "txtFechaUltimoCambio";
            this.txtFechaUltimoCambio.Size = new System.Drawing.Size(107, 20);
            this.txtFechaUltimoCambio.TabIndex = 2;
            this.txtFechaUltimoCambio.TabStop = false;
            this.txtFechaUltimoCambio.Visible = false;
            // 
            // labelControl6
            // 
            this.labelControl6.Location = new System.Drawing.Point(235, 22);
            this.labelControl6.Name = "labelControl6";
            this.labelControl6.Size = new System.Drawing.Size(75, 13);
            this.labelControl6.TabIndex = 4;
            this.labelControl6.Text = "Última conexión";
            this.labelControl6.Visible = false;
            // 
            // txtFechaAlta
            // 
            this.txtFechaAlta.Location = new System.Drawing.Point(5, 42);
            this.txtFechaAlta.Name = "txtFechaAlta";
            this.txtFechaAlta.Size = new System.Drawing.Size(164, 20);
            this.txtFechaAlta.TabIndex = 0;
            this.txtFechaAlta.TabStop = false;
            // 
            // labelControl5
            // 
            this.labelControl5.Location = new System.Drawing.Point(5, 23);
            this.labelControl5.Name = "labelControl5";
            this.labelControl5.Size = new System.Drawing.Size(51, 13);
            this.labelControl5.TabIndex = 3;
            this.labelControl5.Text = "Fecha Alta";
            // 
            // groupControl2
            // 
            this.groupControl2.Controls.Add(this.txtNoEstacion);
            this.groupControl2.Controls.Add(this.labelControl4);
            this.groupControl2.Controls.Add(this.txtNombreComercial);
            this.groupControl2.Controls.Add(this.labelControl2);
            this.groupControl2.Location = new System.Drawing.Point(3, 5);
            this.groupControl2.Name = "groupControl2";
            this.groupControl2.Size = new System.Drawing.Size(392, 74);
            this.groupControl2.TabIndex = 0;
            this.groupControl2.Text = "Datos del cliente";
            // 
            // pnlContent
            // 
            this.pnlContent.Controls.Add(this.groupControl7);
            this.pnlContent.Controls.Add(this.groupControl1);
            this.pnlContent.Controls.Add(this.groupControl3);
            this.pnlContent.Controls.Add(this.groupControl2);
            this.pnlContent.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlContent.Location = new System.Drawing.Point(2, 2);
            this.pnlContent.Name = "pnlContent";
            this.pnlContent.Size = new System.Drawing.Size(905, 546);
            this.pnlContent.TabIndex = 0;
            // 
            // groupControl7
            // 
            this.groupControl7.Controls.Add(this.txtMatriz);
            this.groupControl7.Controls.Add(this.labelControl13);
            this.groupControl7.Controls.Add(this.labelControl12);
            this.groupControl7.Controls.Add(this.txtHostPuerto);
            this.groupControl7.Location = new System.Drawing.Point(3, 332);
            this.groupControl7.Name = "groupControl7";
            this.groupControl7.Size = new System.Drawing.Size(392, 70);
            this.groupControl7.TabIndex = 3;
            this.groupControl7.Text = "Datos de Grupo";
            // 
            // txtMatriz
            // 
            this.txtMatriz.Location = new System.Drawing.Point(5, 42);
            this.txtMatriz.Name = "txtMatriz";
            this.txtMatriz.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Glyph, global::EstandarCliente.AdministrarClientesMdl.Properties.Resources.find, null)});
            this.txtMatriz.Size = new System.Drawing.Size(116, 22);
            this.txtMatriz.TabIndex = 0;
            // 
            // labelControl13
            // 
            this.labelControl13.Location = new System.Drawing.Point(5, 23);
            this.labelControl13.Name = "labelControl13";
            this.labelControl13.Size = new System.Drawing.Size(29, 13);
            this.labelControl13.TabIndex = 2;
            this.labelControl13.Text = "Matriz";
            // 
            // labelControl12
            // 
            this.labelControl12.Location = new System.Drawing.Point(127, 23);
            this.labelControl12.Name = "labelControl12";
            this.labelControl12.Size = new System.Drawing.Size(66, 13);
            this.labelControl12.TabIndex = 3;
            this.labelControl12.Text = "Host y puerto";
            // 
            // txtHostPuerto
            // 
            this.txtHostPuerto.Location = new System.Drawing.Point(127, 42);
            this.txtHostPuerto.Name = "txtHostPuerto";
            this.txtHostPuerto.Size = new System.Drawing.Size(259, 20);
            this.txtHostPuerto.TabIndex = 1;
            this.txtHostPuerto.TabStop = false;
            // 
            // groupControl3
            // 
            this.groupControl3.Controls.Add(this.luDistribuidor);
            this.groupControl3.Controls.Add(this.labelControl11);
            this.groupControl3.Controls.Add(this.txtContacto);
            this.groupControl3.Controls.Add(this.labelControl3);
            this.groupControl3.Controls.Add(this.txtTelefono);
            this.groupControl3.Controls.Add(this.labelControl8);
            this.groupControl3.Controls.Add(this.txtEMail);
            this.groupControl3.Controls.Add(this.labelControl7);
            this.groupControl3.Location = new System.Drawing.Point(3, 85);
            this.groupControl3.Name = "groupControl3";
            this.groupControl3.Size = new System.Drawing.Size(392, 164);
            this.groupControl3.TabIndex = 1;
            this.groupControl3.Text = "Datos Generales";
            // 
            // luDistribuidor
            // 
            this.luDistribuidor.Location = new System.Drawing.Point(5, 132);
            this.luDistribuidor.Name = "luDistribuidor";
            this.luDistribuidor.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.luDistribuidor.Properties.NullText = "";
            this.luDistribuidor.Size = new System.Drawing.Size(173, 20);
            this.luDistribuidor.TabIndex = 3;
            // 
            // labelControl11
            // 
            this.labelControl11.Location = new System.Drawing.Point(5, 113);
            this.labelControl11.Name = "labelControl11";
            this.labelControl11.Size = new System.Drawing.Size(54, 13);
            this.labelControl11.TabIndex = 7;
            this.labelControl11.Text = "Distribuidor";
            // 
            // txtContacto
            // 
            this.txtContacto.Location = new System.Drawing.Point(5, 87);
            this.txtContacto.Name = "txtContacto";
            this.txtContacto.Size = new System.Drawing.Size(263, 20);
            this.txtContacto.TabIndex = 2;
            // 
            // labelControl3
            // 
            this.labelControl3.Location = new System.Drawing.Point(5, 68);
            this.labelControl3.Name = "labelControl3";
            this.labelControl3.Size = new System.Drawing.Size(44, 13);
            this.labelControl3.TabIndex = 6;
            this.labelControl3.Text = "Contacto";
            // 
            // txtTelefono
            // 
            this.txtTelefono.EditValue = "";
            this.txtTelefono.Location = new System.Drawing.Point(275, 42);
            this.txtTelefono.Name = "txtTelefono";
            this.txtTelefono.Size = new System.Drawing.Size(112, 20);
            this.txtTelefono.TabIndex = 1;
            // 
            // labelControl8
            // 
            this.labelControl8.Location = new System.Drawing.Point(275, 23);
            this.labelControl8.Name = "labelControl8";
            this.labelControl8.Size = new System.Drawing.Size(42, 13);
            this.labelControl8.TabIndex = 5;
            this.labelControl8.Text = "Teléfono";
            // 
            // txtEMail
            // 
            this.txtEMail.Location = new System.Drawing.Point(5, 42);
            this.txtEMail.Name = "txtEMail";
            this.txtEMail.Size = new System.Drawing.Size(264, 20);
            this.txtEMail.TabIndex = 0;
            // 
            // labelControl7
            // 
            this.labelControl7.Location = new System.Drawing.Point(5, 23);
            this.labelControl7.Name = "labelControl7";
            this.labelControl7.Size = new System.Drawing.Size(28, 13);
            this.labelControl7.TabIndex = 4;
            this.labelControl7.Text = "E-Mail";
            // 
            // pnlDomicilios
            // 
            this.pnlDomicilios.Controls.Add(this.pnlContent);
            this.pnlDomicilios.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlDomicilios.Location = new System.Drawing.Point(0, 50);
            this.pnlDomicilios.Name = "pnlDomicilios";
            this.pnlDomicilios.Size = new System.Drawing.Size(909, 550);
            this.pnlDomicilios.TabIndex = 1;
            // 
            // VMAdministrarClientes
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.pnlDomicilios);
            this.Controls.Add(this.titulo1);
            this.Name = "VMAdministrarClientes";
            this.Size = new System.Drawing.Size(909, 600);
            ((System.ComponentModel.ISupportInitialize)(this.txtNombreComercial.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtNoEstacion.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.groupControl1)).EndInit();
            this.groupControl1.ResumeLayout(false);
            this.groupControl1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.chkActivo.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtFechaUltimoCambio.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtFechaAlta.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.groupControl2)).EndInit();
            this.groupControl2.ResumeLayout(false);
            this.groupControl2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pnlContent)).EndInit();
            this.pnlContent.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.groupControl7)).EndInit();
            this.groupControl7.ResumeLayout(false);
            this.groupControl7.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.txtMatriz.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtHostPuerto.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.groupControl3)).EndInit();
            this.groupControl3.ResumeLayout(false);
            this.groupControl3.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.luDistribuidor.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtContacto.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtTelefono.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtEMail.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pnlDomicilios)).EndInit();
            this.pnlDomicilios.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private ControlesEstandar.Titulo titulo1;
        private DevExpress.XtraEditors.LabelControl labelControl2;
        private DevExpress.XtraEditors.TextEdit txtNombreComercial;
        private DevExpress.XtraEditors.TextEdit txtNoEstacion;
        private DevExpress.XtraEditors.LabelControl labelControl4;
        private DevExpress.XtraEditors.GroupControl groupControl1;
        private DevExpress.XtraEditors.CheckEdit chkActivo;
        private DevExpress.XtraEditors.TextEdit txtFechaUltimoCambio;
        private DevExpress.XtraEditors.LabelControl labelControl6;
        private DevExpress.XtraEditors.TextEdit txtFechaAlta;
        private DevExpress.XtraEditors.LabelControl labelControl5;
        private DevExpress.XtraEditors.GroupControl groupControl2;
        private DevExpress.XtraEditors.PanelControl pnlContent;
        private DevExpress.XtraEditors.GroupControl groupControl3;
        private DevExpress.XtraEditors.TextEdit txtEMail;
        private DevExpress.XtraEditors.LabelControl labelControl7;
        private DevExpress.XtraEditors.TextEdit txtTelefono;
        private DevExpress.XtraEditors.LabelControl labelControl8;
        private DevExpress.XtraEditors.PanelControl pnlDomicilios;
        private DevExpress.XtraEditors.TextEdit txtContacto;
        private DevExpress.XtraEditors.LabelControl labelControl3;
        private DevExpress.XtraEditors.LookUpEdit luDistribuidor;
        private DevExpress.XtraEditors.LabelControl labelControl11;
        private DevExpress.XtraEditors.GroupControl groupControl7;
        private DevExpress.XtraEditors.LabelControl labelControl13;
        private DevExpress.XtraEditors.LabelControl labelControl12;
        private DevExpress.XtraEditors.TextEdit txtHostPuerto;
        private DevExpress.XtraEditors.ButtonEdit txtMatriz;
    }
}

