SET TERM !!;

-- Agregar la tabla Dispositivos Moviles
CREATE TABLE MOVILES (
    TELEFONO CHAR(10) NOT NULL,
    RESPONSABLE VARCHAR(100),
    PASSWORD VARCHAR(20),
    ACTIVO CHAR(1)
)!!
COMMIT!!

ALTER TABLE MOVILES ADD PRIMARY KEY (TELEFONO)!!

COMMIT!!

SET TERM ; !!
