
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v90/MS.VSIPCC.v90/ms.practices.scsf.2008apr/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace EstandarCliente.AdministrarUsuariosMdl
{
    partial class VLAdministrarUsuarios
    {
        /// <summary>
        /// The presenter used by this view.
        /// </summary>
        private EstandarCliente.AdministrarUsuariosMdl.VLAdministrarUsuariosPresenter _presenter = null;

        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_presenter != null)
                    _presenter.Dispose();

                if (components != null)
                    components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.titulo1 = new ControlesEstandar.Titulo();
            this.panel1 = new System.Windows.Forms.Panel();
            this.luActivos = new DevExpress.XtraEditors.GridLookUpEdit();
            this.gridLookUpEdit1View = new DevExpress.XtraGrid.Views.Grid.GridView();
            this.labelControl2 = new DevExpress.XtraEditors.LabelControl();
            this.txtNombre = new DevExpress.XtraEditors.TextEdit();
            this.labelControl1 = new DevExpress.XtraEditors.LabelControl();
            this.pnlContent = new System.Windows.Forms.Panel();
            this.grdListado = new DevExpress.XtraGrid.GridControl();
            this.gridView1 = new DevExpress.XtraGrid.Views.Grid.GridView();
            this.labelControl3 = new DevExpress.XtraEditors.LabelControl();
            this.luDistribuidor = new DevExpress.XtraEditors.LookUpEdit();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.luActivos.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridLookUpEdit1View)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtNombre.Properties)).BeginInit();
            this.pnlContent.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdListado)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridView1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.luDistribuidor.Properties)).BeginInit();
            this.SuspendLayout();
            // 
            // titulo1
            // 
            this.titulo1.BackColor1 = System.Drawing.Color.LightSkyBlue;
            this.titulo1.BackColor2 = System.Drawing.Color.RoyalBlue;
            this.titulo1.Dock = System.Windows.Forms.DockStyle.Top;
            this.titulo1.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.titulo1.Location = new System.Drawing.Point(0, 0);
            this.titulo1.Name = "titulo1";
            this.titulo1.Size = new System.Drawing.Size(834, 50);
            this.titulo1.TabIndex = 0;
            this.titulo1.TituloMenu = null;
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.RoyalBlue;
            this.panel1.Controls.Add(this.labelControl3);
            this.panel1.Controls.Add(this.luDistribuidor);
            this.panel1.Controls.Add(this.luActivos);
            this.panel1.Controls.Add(this.labelControl2);
            this.panel1.Controls.Add(this.txtNombre);
            this.panel1.Controls.Add(this.labelControl1);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 50);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(834, 53);
            this.panel1.TabIndex = 1;
            // 
            // luActivos
            // 
            this.luActivos.Location = new System.Drawing.Point(253, 25);
            this.luActivos.Name = "luActivos";
            this.luActivos.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.luActivos.Properties.NullText = "";
            this.luActivos.Properties.View = this.gridLookUpEdit1View;
            this.luActivos.Size = new System.Drawing.Size(100, 20);
            this.luActivos.TabIndex = 5;
            // 
            // gridLookUpEdit1View
            // 
            this.gridLookUpEdit1View.FocusRectStyle = DevExpress.XtraGrid.Views.Grid.DrawFocusRectStyle.RowFocus;
            this.gridLookUpEdit1View.Name = "gridLookUpEdit1View";
            this.gridLookUpEdit1View.OptionsSelection.EnableAppearanceFocusedCell = false;
            this.gridLookUpEdit1View.OptionsView.ShowGroupPanel = false;
            // 
            // labelControl2
            // 
            this.labelControl2.Appearance.ForeColor = System.Drawing.Color.White;
            this.labelControl2.Appearance.Options.UseForeColor = true;
            this.labelControl2.Location = new System.Drawing.Point(253, 6);
            this.labelControl2.Name = "labelControl2";
            this.labelControl2.Size = new System.Drawing.Size(30, 13);
            this.labelControl2.TabIndex = 4;
            this.labelControl2.Text = "Activo";
            // 
            // txtNombre
            // 
            this.txtNombre.Location = new System.Drawing.Point(3, 25);
            this.txtNombre.Name = "txtNombre";
            this.txtNombre.Size = new System.Drawing.Size(244, 20);
            this.txtNombre.TabIndex = 2;
            // 
            // labelControl1
            // 
            this.labelControl1.Appearance.ForeColor = System.Drawing.Color.White;
            this.labelControl1.Appearance.Options.UseForeColor = true;
            this.labelControl1.Location = new System.Drawing.Point(3, 6);
            this.labelControl1.Name = "labelControl1";
            this.labelControl1.Size = new System.Drawing.Size(37, 13);
            this.labelControl1.TabIndex = 1;
            this.labelControl1.Text = "Nombre";
            // 
            // pnlContent
            // 
            this.pnlContent.Controls.Add(this.grdListado);
            this.pnlContent.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlContent.Location = new System.Drawing.Point(0, 103);
            this.pnlContent.Name = "pnlContent";
            this.pnlContent.Size = new System.Drawing.Size(834, 369);
            this.pnlContent.TabIndex = 2;
            // 
            // grdListado
            // 
            this.grdListado.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grdListado.EmbeddedNavigator.Name = "";
            this.grdListado.Location = new System.Drawing.Point(0, 0);
            this.grdListado.MainView = this.gridView1;
            this.grdListado.Name = "grdListado";
            this.grdListado.Size = new System.Drawing.Size(834, 369);
            this.grdListado.TabIndex = 0;
            this.grdListado.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] {
            this.gridView1});
            // 
            // gridView1
            // 
            this.gridView1.GridControl = this.grdListado;
            this.gridView1.Name = "gridView1";
            // 
            // labelControl3
            // 
            this.labelControl3.Appearance.ForeColor = System.Drawing.Color.White;
            this.labelControl3.Appearance.Options.UseForeColor = true;
            this.labelControl3.Location = new System.Drawing.Point(359, 6);
            this.labelControl3.Name = "labelControl3";
            this.labelControl3.Size = new System.Drawing.Size(54, 13);
            this.labelControl3.TabIndex = 14;
            this.labelControl3.Text = "Distribuidor";
            // 
            // luDistribuidor
            // 
            this.luDistribuidor.Location = new System.Drawing.Point(359, 25);
            this.luDistribuidor.Name = "luDistribuidor";
            this.luDistribuidor.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.luDistribuidor.Properties.NullText = "";
            this.luDistribuidor.Size = new System.Drawing.Size(146, 20);
            this.luDistribuidor.TabIndex = 13;
            // 
            // VLAdministrarUsuarios
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.pnlContent);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.titulo1);
            this.Name = "VLAdministrarUsuarios";
            this.Size = new System.Drawing.Size(834, 472);
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.luActivos.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridLookUpEdit1View)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtNombre.Properties)).EndInit();
            this.pnlContent.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.grdListado)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridView1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.luDistribuidor.Properties)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private ControlesEstandar.Titulo titulo1;
        private System.Windows.Forms.Panel panel1;
        private DevExpress.XtraEditors.LabelControl labelControl1;
        private DevExpress.XtraEditors.LabelControl labelControl2;
        private DevExpress.XtraEditors.TextEdit txtNombre;
        private System.Windows.Forms.Panel pnlContent;
        private DevExpress.XtraGrid.GridControl grdListado;
        private DevExpress.XtraGrid.Views.Grid.GridView gridView1;
        private DevExpress.XtraEditors.GridLookUpEdit luActivos;
        private DevExpress.XtraGrid.Views.Grid.GridView gridLookUpEdit1View;
        private DevExpress.XtraEditors.LabelControl labelControl3;
        private DevExpress.XtraEditors.LookUpEdit luDistribuidor;
    }
}

