
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v90/MS.VSIPCC.v90/ms.practices.scsf.2008apr/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace EstandarCliente.SesionMdl
{
    partial class VSesion
    {
        /// <summary>
        /// The presenter used by this view.
        /// </summary>
        private EstandarCliente.SesionMdl.VSesionPresenter _presenter = null;

        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_presenter != null)
                    _presenter.Dispose();

                if (components != null)
                    components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.btnCambiarContrasena = new DevExpress.XtraEditors.HyperLinkEdit();
            this.luUsuario = new DevExpress.XtraEditors.LookUpEdit();
            this.btnAceptar = new DevExpress.XtraEditors.SimpleButton();
            this.labelControl2 = new DevExpress.XtraEditors.LabelControl();
            this.btnCancelar = new DevExpress.XtraEditors.SimpleButton();
            this.labelControl1 = new DevExpress.XtraEditors.LabelControl();
            this.panel1 = new System.Windows.Forms.Panel();
            this.lblVersion = new DevExpress.XtraEditors.LabelControl();
            this.txtContraseña = new System.Windows.Forms.TextBox();
            ((System.ComponentModel.ISupportInitialize)(this.btnCambiarContrasena.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.luUsuario.Properties)).BeginInit();
            this.panel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // btnCambiarContrasena
            // 
            this.btnCambiarContrasena.EditValue = "Cambiar contraseña";
            this.btnCambiarContrasena.Location = new System.Drawing.Point(47, 175);
            this.btnCambiarContrasena.Name = "btnCambiarContrasena";
            this.btnCambiarContrasena.Properties.Appearance.BackColor = System.Drawing.Color.Transparent;
            this.btnCambiarContrasena.Properties.Appearance.Font = new System.Drawing.Font("Tahoma", 8F);
            this.btnCambiarContrasena.Properties.Appearance.ForeColor = System.Drawing.Color.Black;
            this.btnCambiarContrasena.Properties.Appearance.Options.UseBackColor = true;
            this.btnCambiarContrasena.Properties.Appearance.Options.UseFont = true;
            this.btnCambiarContrasena.Properties.Appearance.Options.UseForeColor = true;
            this.btnCambiarContrasena.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
            this.btnCambiarContrasena.Size = new System.Drawing.Size(109, 17);
            this.btnCambiarContrasena.TabIndex = 13;
            // 
            // luUsuario
            // 
            this.luUsuario.Location = new System.Drawing.Point(4, 25);
            this.luUsuario.Name = "luUsuario";
            this.luUsuario.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.luUsuario.Properties.ButtonsStyle = DevExpress.XtraEditors.Controls.BorderStyles.UltraFlat;
            this.luUsuario.Properties.LookAndFeel.SkinName = "Black";
            this.luUsuario.Properties.LookAndFeel.Style = DevExpress.LookAndFeel.LookAndFeelStyle.Flat;
            this.luUsuario.Properties.LookAndFeel.UseDefaultLookAndFeel = false;
            this.luUsuario.Properties.NullText = "";
            this.luUsuario.Size = new System.Drawing.Size(160, 22);
            this.luUsuario.TabIndex = 7;
            // 
            // btnAceptar
            // 
            this.btnAceptar.Image = global::EstandarCliente.SesionMdl.Properties.Resources.aceptar;
            this.btnAceptar.Location = new System.Drawing.Point(15, 198);
            this.btnAceptar.LookAndFeel.SkinName = "Blue";
            this.btnAceptar.LookAndFeel.Style = DevExpress.LookAndFeel.LookAndFeelStyle.Flat;
            this.btnAceptar.LookAndFeel.UseDefaultLookAndFeel = false;
            this.btnAceptar.Name = "btnAceptar";
            this.btnAceptar.Size = new System.Drawing.Size(82, 35);
            this.btnAceptar.TabIndex = 9;
            this.btnAceptar.Text = "Aceptar";
            // 
            // labelControl2
            // 
            this.labelControl2.Appearance.Font = new System.Drawing.Font("Tahoma", 10F, System.Drawing.FontStyle.Bold);
            this.labelControl2.Appearance.ForeColor = System.Drawing.Color.Black;
            this.labelControl2.Appearance.Options.UseFont = true;
            this.labelControl2.Appearance.Options.UseForeColor = true;
            this.labelControl2.Location = new System.Drawing.Point(3, 64);
            this.labelControl2.Name = "labelControl2";
            this.labelControl2.Size = new System.Drawing.Size(75, 16);
            this.labelControl2.TabIndex = 12;
            this.labelControl2.Text = "Contraseña";
            // 
            // btnCancelar
            // 
            this.btnCancelar.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnCancelar.Image = global::EstandarCliente.SesionMdl.Properties.Resources.cancelar;
            this.btnCancelar.Location = new System.Drawing.Point(103, 198);
            this.btnCancelar.LookAndFeel.SkinName = "Black";
            this.btnCancelar.LookAndFeel.Style = DevExpress.LookAndFeel.LookAndFeelStyle.Flat;
            this.btnCancelar.LookAndFeel.UseDefaultLookAndFeel = false;
            this.btnCancelar.Name = "btnCancelar";
            this.btnCancelar.Size = new System.Drawing.Size(82, 35);
            this.btnCancelar.TabIndex = 10;
            this.btnCancelar.Text = "Cancelar";
            // 
            // labelControl1
            // 
            this.labelControl1.Appearance.Font = new System.Drawing.Font("Tahoma", 10F, System.Drawing.FontStyle.Bold);
            this.labelControl1.Appearance.ForeColor = System.Drawing.Color.Black;
            this.labelControl1.Appearance.Options.UseFont = true;
            this.labelControl1.Appearance.Options.UseForeColor = true;
            this.labelControl1.Location = new System.Drawing.Point(3, 3);
            this.labelControl1.Name = "labelControl1";
            this.labelControl1.Size = new System.Drawing.Size(48, 16);
            this.labelControl1.TabIndex = 11;
            this.labelControl1.Text = "Usuario";
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.Transparent;
            this.panel1.Controls.Add(this.txtContraseña);
            this.panel1.Controls.Add(this.labelControl1);
            this.panel1.Controls.Add(this.luUsuario);
            this.panel1.Controls.Add(this.labelControl2);
            this.panel1.Location = new System.Drawing.Point(18, 42);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(167, 127);
            this.panel1.TabIndex = 14;
            // 
            // lblVersion
            // 
            this.lblVersion.Appearance.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Bold);
            this.lblVersion.Appearance.ForeColor = System.Drawing.Color.White;
            this.lblVersion.Appearance.Options.UseFont = true;
            this.lblVersion.Appearance.Options.UseForeColor = true;
            this.lblVersion.Location = new System.Drawing.Point(398, 272);
            this.lblVersion.Name = "lblVersion";
            this.lblVersion.Size = new System.Drawing.Size(85, 13);
            this.lblVersion.TabIndex = 15;
            this.lblVersion.Text = "Versión: 2.2.0.0";
            // 
            // txtContraseña
            // 
            this.txtContraseña.Font = new System.Drawing.Font("Wingdings", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(2)));
            this.txtContraseña.Location = new System.Drawing.Point(4, 86);
            this.txtContraseña.Name = "txtContraseña";
            this.txtContraseña.Size = new System.Drawing.Size(160, 20);
            this.txtContraseña.TabIndex = 16;
            // 
            // VSesion
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = global::EstandarCliente.SesionMdl.Properties.Resources.VSesion;
            this.CausesValidation = false;
            this.Controls.Add(this.lblVersion);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.btnCambiarContrasena);
            this.Controls.Add(this.btnAceptar);
            this.Controls.Add(this.btnCancelar);
            this.Name = "VSesion";
            this.Size = new System.Drawing.Size(500, 300);
            ((System.ComponentModel.ISupportInitialize)(this.btnCambiarContrasena.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.luUsuario.Properties)).EndInit();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private DevExpress.XtraEditors.HyperLinkEdit btnCambiarContrasena;
        private DevExpress.XtraEditors.LookUpEdit luUsuario;
        private DevExpress.XtraEditors.LabelControl labelControl2;
        private DevExpress.XtraEditors.LabelControl labelControl1;
        private System.Windows.Forms.Panel panel1;
        private DevExpress.XtraEditors.LabelControl lblVersion;
        public DevExpress.XtraEditors.SimpleButton btnAceptar;
        public DevExpress.XtraEditors.SimpleButton btnCancelar;
        private System.Windows.Forms.TextBox txtContraseña;
    }
}

