//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by this guidance package as part of the solution template
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/03-01-010-How_to_Create_Smart_Client_Solutions.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace EstandarCliente.Infrastructure.Interface.Constants
{
    /// <summary>
    /// Constants for UI extension site names.
    /// </summary>
    public class UIExtensionSiteNames
    {
        /// <summary>
        /// The extension site for the main menu.
        /// </summary>
        public const string Ribbon = "Ribbon";
        public const string MainMenu = "MainMenu";
        public const string MenuCatalogo = "MenuCatalogo";
        public const string PaginaMenu = "PaginaMenu";
        public const string RightWorkspace = "RightWorkspace";
        public const string LeftWorkspace = "LeftWorkspace";

        /// <summary>
        /// The extension site for the main toolbar.
        /// </summary>
        public const string MainToolbar = "MainToolbar";

        /// <summary>
        /// The extension site for the main status bar.
        /// </summary>
        public const string MainStatus = "MainStatus";

        public const string Complejos = "Complejos";
        public const string Simples = "Simples";
        public const string Documentos = "Documentos";
        public const string Consultas = "Consultas";
        
        public const string ApplicationMenu = "ApplicationMenu";
        public const string ApplicationMenuNuevo = "ApplicationMenuNuevo";
    }
}
